inherit_from:
  ~/.config/rubocop/rubocop.yml

AllCops:
  TargetRubyVersion: 2.4

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes
